version: 2
updates:
  # rust
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
  # actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
