[process]
command = "wob"
args = []

[[commands]]
name = "volume_up"
command = "amixer"
args = ["sset", "Master", "5%+"]

[[commands]]
name = "volume_down"
command = "amixer"
args = ["sset", "Master", "5%-"]

[[commands]]
name = "brightness_down"
command = "brightnessctl"
args = ["s", "5%-"]

[[commands]]
name = "brightness_up"
command = "brightnessctl"
args = ["s", "5%+"]
